/* Recent Post with thumbnails 
*  Script by bloggerplugins.org
*  Re-layout by SaliproIT
*  Site: http://salipropham.blogspot.com
*/ 
var postTitleOriginal,myLink,myDiv,myImage,mySeparator,main,float_clear=!1,flag=0;
function bprecentpostswiththumbnails(h){for(var j=0;j<numberOfPosts&&j!=h.feed.entry.length;j++){var e,g=h.feed.entry[j],k=g.title.$t;postTitleOriginal=k;isNaN(titleLength)||0==titleLength?k="":k.length>titleLength&&(k=k.substring(0,titleLength)+"...");var n="";for(e=0;e<g.link.length;e++){if("replies"==g.link[e].rel&&"text/html"==g.link[e].type)var l=g.link[e].title,o=g.link[e].href;if("alternate"==g.link[e].rel){n=g.link[e].href;break}}if(!0==showThumbs){var f="";try{f=g.media$thumbnail.url,f=f.replace("/s72-c/",
"/s"+imgDim+"-c/")}catch(t){if(e="content"in g?g.content.$t:"",""==f&&!1==mediaThumbsOnly&&(regex=/http\:\/\/www\.youtube(-nocookie){0,1}\.com\/(v){0,1}(embed){0,1}\/(([^"&?' ]*))/,videoIds=e.match(regex),null!=videoIds&&(videoId=videoIds[4]),null!=videoIds&&null!=videoId&&(f="http://img.youtube.com/vi/"+videoId+"/2.jpg")),""==f&&!1==mediaThumbsOnly)a=e.indexOf("<img"),b=e.indexOf('src="',a),c=e.indexOf('"',b+5),d=e.substr(b+5,c-b-5),-1!=a&&(-1!=b&&-1!=c&&""!=d)&&(f=d)}-1!=f.indexOf("static.flickr.com")&&
(f=f.replace("_b_t.jpg","_s.jpg"),f=f.replace("_m_t.jpg","_s.jpg"),f=f.replace("_s_t.jpg","_s.jpg"),f=f.replace("_b.jpg","_s.jpg"),f=f.replace("_m.jpg","_s.jpg"));if(""==f&&!0==showNoImage){f="http://2.bp.blogspot.com/-erTXCq61ULM/TmHYAQBZ0GI/AAAAAAAACCs/6cBX54Dn6Gs/s72-c/default.png";try{""!=defaultImage&&(f=defaultImage)}catch(u){}f=f.replace("/s72-c/","/s"+imgDim+"-c/")}}if(!0==showPostDate)var m=g.published.$t,p=m.substring(0,4),q=m.substring(5,7),m=m.substring(8,10),r=[,"Jan","Feb","Mar","Apr",
"May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];code="";main=document.getElementById("bp_recent");contDiv=document.createElement("div");contDiv.setAttribute("class","recent-post-cont");main.appendChild(contDiv);myDiv=document.createElement("div");myDiv.setAttribute("class","bp_item_title");e=createLink(n,"_top",postTitleOriginal);""!=main.innerHTML&&(mySeparator=createDiv("bp_recent_separator"),main.appendChild(mySeparator));""!=k&&myDiv.appendChild(e);contDiv.appendChild(myDiv);""!=k&&(e.innerHTML=
k);if(!0==showThumbs&&""!=f){myImage=document.createElement("img");myImage.setAttribute("src",f);"none"!=imgFloat&&(float_clear=!0,myImage.style.cssFloat=imgFloat,myImage.style.styleFloat=imgFloat);try{0!=myMargin&&(myImage.style.margin=myMargin+"px")}catch(v){}myImage.setAttribute("alt",postTitleOriginal);myImage.setAttribute("width",imgDim);myImage.setAttribute("height",imgDim);e=document.createElement("a");e.setAttribute("href",n+"?utm_source=bp_recent&utm-medium=gadget&utm_campaign=bp_recent");
e.setAttribute("target","_top");e.setAttribute("title",postTitleOriginal);e.appendChild(myImage);myDiv=document.createElement("div");myDiv.setAttribute("class","bp_item_thumb");myDiv.appendChild(e);contDiv.appendChild(myDiv)}try{var i="content"in g?g.content.$t:"summary"in g?g.summary.$t:"",i=i.replace(/<\S[^>]*>/g,"");if(!0==showSummary){myDiv=createDiv("bp_item_summary");if(i.length<summaryLength)myDiv.appendChild(document.createTextNode(i));else{var i=i.substring(0,summaryLength),s=i.lastIndexOf(" "),
i=i.substring(0,s);myDiv.appendChild(document.createTextNode(i+"..."))}contDiv.appendChild(myDiv)}}catch(w){}myDiv=createDiv("bp_item_meta");myDiv.style.clear="both";myDiv.style.marginBottom="4px";!0==showPostDate&&(myDiv.appendChild(document.createTextNode(r[parseInt(q,10)]+"-"+m+"-"+p)),flag=1);!0==showCommentCount&&(1==flag&&myDiv.appendChild(document.createTextNode(" | ")),"1 Comments"==l&&(l="1 Comment"),"0 Comments"==l&&(l="No Comments"),e=createLink(o,"_top",l+" on "+postTitleOriginal),myDiv.appendChild(e),
e.innerHTML=l,flag=1);!0==showReadMore&&(1==flag&&myDiv.appendChild(document.createTextNode(" | ")),e=createLink(n,"_top",postTitleOriginal),myDiv.appendChild(e),e.innerHTML=readMore+" &raquo;",flag=1);1==flag&&contDiv.appendChild(myDiv)}!0==float_clear&&"none"!=imgFloat&&(myDiv=createDiv("bp_clear_float"),myDiv.style.clear=imgFloat,contDiv.appendChild(myDiv));document.getElementById("bp_recent_link").style.backgroundImage="url('http://3.bp.blogspot.com/-H8WPIh3wjr4/TmHnuo9tnnI/AAAAAAAACDE/_yuVqfb1HAk/blogger-widgets.png')";
document.getElementById("bp_recent_link").style.backgroundRepeat="no-repeat";try{0!=myMargin&&("left"==imgFloat&&0==flag)&&(document.getElementById("bp_recent_link").style.marginLeft=myMargin+"px")}catch(x){}}function createDiv(h){var j=document.createElement("div");j.setAttribute("class",h);return j}
function createLink(h,j,e){var g=document.createElement("a");"#comment-form"==h.substring(h.length-13,h.length)?(h=h.substring(0,h.length-13)+"?utm_source=bp_recent&utm-medium=gadget&utm_campaign=bp_recent#comment-form",g.setAttribute("href",h)):g.setAttribute("href",h+"?utm_source=BP_recent&utm-medium=gadget&utm_campaign=bp_recent");g.setAttribute("target",j);g.setAttribute("title",e);return g};